### ISSUE TITLE
Need function getChallengeThreshold

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-JVM#5]
def getChallengeThreshold(userId: String, accountId: String, transactionRequestType: String, currency: String): (BigDecimal, String)

returns the amount and currency (three letter ISO code) as a sanity check.

**Comment by kassapo** [comment]
Is accountId a UUID? And even it is - how was it computed? Does it include the bank? Sure? Otherwise the bankId is required.

**Comment by kassapo** [comment]
Why wait for anyone to review this after six weeks?
